### ISSUE TITLE
Jetty 9.4 Session Config

### ISSUE THREAD

**Issue by botic** [grob/httpserver#6]
I think they changed the session implementation and so some config code like `enableSessions()` needs some updates: http://www.eclipse.org/jetty/documentation/9.4.x/upgrading-jetty.html#_session_management

**Comment by botic** [comment]
Config:
```
    // configure the server
    server = httpServer.build()
        .enableSessions({
            "name": "collosession",
        })
        // serve applications
        .serveApplication("/", module.resolve("./router-backend"), {
            "virtualHosts": config.get("backend:vhosts")
        })
        .serveApplication("/", module.resolve("./router-guestpass"), {
            "virtualHosts": config.get("guestpass:vhosts")
        });
```
Result:
```
13 Apr 2017 11:02:12,569 INFO  [main]  - Logging initialized @1153ms to org.eclipse.jetty.util.log.Slf4jLog
13 Apr 2017 11:02:12,671 INFO  [main]  - Initializing application
TypeError: [JavaPackage org.eclipse.jetty.server.session.HashSessionIdManager] is not a function, it is object.
	at httpserver/lib/httpserver.js:210 (anonymous)
	at httpserver/lib/builder.js:49 (anonymous)
	at /Users/philipp/Code/collodion/app/main.js:50 (anonymous)
	at /Users/philipp/Code/collodion/app/main.js:120
```

**Comment by sclee15** [comment]
Yes. I see it too..
I just installed this httpserver package.
and i experienced same.

it would be awesome this package works with 9.4
